.headers on
.output geonames_pairs.csv

SELECT c2.TRANSL_CD AS TRANSL_CD, c2.UNI AS SRC_UNI, c2.NT AS SRC_NT, c2.FULL_NAME_RO AS SRC_FULL_NAME_RO, c2.FULL_NAME_RG AS SRC_FULL_NAME_RG, c1.UNI AS DEST_UNI, c1.NT AS DEST_NT, c1.FULL_NAME_RO AS DEST_FULL_NAME_RO, c1.FULL_NAME_RG AS DEST_FULL_NAME_RG, c2.LC AS LC
FROM countries AS c1
LEFT JOIN countries AS c2
ON c2.NAME_LINK = c1.UNI
WHERE c2.TRANSL_CD <> "NOT_TRANSLITERATED" AND c2.TRANSL_CD <> ""
ORDER BY c2.TRANSL_CD DESC
;
